//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Scripts/Input/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""ShmupControls"",
            ""id"": ""3009ba66-38ac-4c49-9bea-48d90a7a2696"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""2ee19ed3-9b61-422e-812c-15d9bc3b95fa"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Basic Attack"",
                    ""type"": ""Button"",
                    ""id"": ""c5ab4426-b5bd-430f-b956-543027120251"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alternate Attack"",
                    ""type"": ""Button"",
                    ""id"": ""2c87976b-10f1-4017-9066-ff9f8fbd4725"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""0b2afd96-e5ca-426b-bc3b-95815b991977"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD controls"",
                    ""id"": ""5b6749c6-8451-4906-a750-759ba5e39d1e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f47796a9-c699-47b3-bd76-24cbe631997a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f61c99bc-5167-43bf-9761-cf9b7e2aaec6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6aa67bb7-f36b-4c3a-b11b-b1887515a1db"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""074ab158-8aac-4436-b0c7-b03320a16593"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3e5a9146-9760-437d-bc55-2e59a9e21c9b"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24f150bc-c030-4cd6-b637-ae2492e8d47f"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Basic Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5aeb30a8-2c3e-444a-8692-13776f7fe615"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Basic Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0f43d6f-8010-4b87-baa8-9fd094f0162d"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alternate Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e15820df-0691-4efb-b04a-af6cf90e8277"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ShmupControls
        m_ShmupControls = asset.FindActionMap("ShmupControls", throwIfNotFound: true);
        m_ShmupControls_Move = m_ShmupControls.FindAction("Move", throwIfNotFound: true);
        m_ShmupControls_BasicAttack = m_ShmupControls.FindAction("Basic Attack", throwIfNotFound: true);
        m_ShmupControls_AlternateAttack = m_ShmupControls.FindAction("Alternate Attack", throwIfNotFound: true);
        m_ShmupControls_Pause = m_ShmupControls.FindAction("Pause", throwIfNotFound: true);
    }

    ~@PlayerControls()
    {
        UnityEngine.Debug.Assert(!m_ShmupControls.enabled, "This will cause a leak and performance issues, PlayerControls.ShmupControls.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ShmupControls
    private readonly InputActionMap m_ShmupControls;
    private List<IShmupControlsActions> m_ShmupControlsActionsCallbackInterfaces = new List<IShmupControlsActions>();
    private readonly InputAction m_ShmupControls_Move;
    private readonly InputAction m_ShmupControls_BasicAttack;
    private readonly InputAction m_ShmupControls_AlternateAttack;
    private readonly InputAction m_ShmupControls_Pause;
    public struct ShmupControlsActions
    {
        private @PlayerControls m_Wrapper;
        public ShmupControlsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_ShmupControls_Move;
        public InputAction @BasicAttack => m_Wrapper.m_ShmupControls_BasicAttack;
        public InputAction @AlternateAttack => m_Wrapper.m_ShmupControls_AlternateAttack;
        public InputAction @Pause => m_Wrapper.m_ShmupControls_Pause;
        public InputActionMap Get() { return m_Wrapper.m_ShmupControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ShmupControlsActions set) { return set.Get(); }
        public void AddCallbacks(IShmupControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_ShmupControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ShmupControlsActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @BasicAttack.started += instance.OnBasicAttack;
            @BasicAttack.performed += instance.OnBasicAttack;
            @BasicAttack.canceled += instance.OnBasicAttack;
            @AlternateAttack.started += instance.OnAlternateAttack;
            @AlternateAttack.performed += instance.OnAlternateAttack;
            @AlternateAttack.canceled += instance.OnAlternateAttack;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
        }

        private void UnregisterCallbacks(IShmupControlsActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @BasicAttack.started -= instance.OnBasicAttack;
            @BasicAttack.performed -= instance.OnBasicAttack;
            @BasicAttack.canceled -= instance.OnBasicAttack;
            @AlternateAttack.started -= instance.OnAlternateAttack;
            @AlternateAttack.performed -= instance.OnAlternateAttack;
            @AlternateAttack.canceled -= instance.OnAlternateAttack;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
        }

        public void RemoveCallbacks(IShmupControlsActions instance)
        {
            if (m_Wrapper.m_ShmupControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IShmupControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_ShmupControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ShmupControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ShmupControlsActions @ShmupControls => new ShmupControlsActions(this);
    public interface IShmupControlsActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnBasicAttack(InputAction.CallbackContext context);
        void OnAlternateAttack(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
    }
}
